---
ignore:
  - "tests/*"
  - "benchmarks/*"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    patch:
      default:
        enabled: false

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

cli:
  plugins:
    pycoverage:
      report_type: "json"
