[project]
authors = ["Jiří Liška <70215056+liskajiri@users.noreply.github.com>"]
channels = ["https://prefix.dev/conda-forge"]
description = "Library for deep learning & neural networks"
name = "needle"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[environments]
jupyter = ["jupyter"]
lint = ["lint"]
dev = ["dev", "jupyter"]

[dependencies]
numpy = ">=2.2.0,<3"

[feature.jupyter.dependencies]
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.29.5,<7"

[feature.lint.dependencies]
ruff = ">=0.8.2,<0.9"
pre-commit = ">=4.0.1,<5"
pre-commit-hooks = ">=5.0.0,<6"
clang-format = ">=19.1.5,<20"

[feature.lint.tasks]
format = "clang-format -i src/*.cc src/*.cu"
lint = "pre-commit run --all-files --color=always --show-diff-on-failure"
style = { depends-on = ["format", "lint"] }

[feature.dev.dependencies]
cmake = ">=3.31.2,<4"
pybind11 = ">=2.13.6,<3"
pytest = ">=8.3.4,<9"
pytest-benchmark = ">=5.1.0,<6"
pygal = ">=3.0.5,<4"
numdifftools = ">=0.9.41,<0.10"

[feature.dev.tasks]
clean = { cmd = [
    "rm", "-rf",
    "hw*/build",
    "hw*/python/needle/backend_ndarray/ndarray_backend*.so"
    ]}
# make: possible to set inputs {inputs = ["src/ndarray_backend_cpu.cc", "src/ndarray_backend_cuda.cu"]}
make = {cmd = "mkdir -p build && cd build && cmake .. && make"}
test = {cmd = "python -m pytest --benchmark-skip", depends-on = ["make"]}
matmul_benchmark = {cmd = "python -m pytest tests/test_benchmarks.py --benchmark-autosave --benchmark-save-data --benchmark-histogram='benchmark_results/matmul_graph'", depends-on = ["make"]}

[activation]
env = {PYTHONPATH = "./python:./apps"}
