[tool.pytest.ini_options]
testpaths = "tests/"
markers = [
    "slow: marks tests as slow",
    "proptest: marks tests as property tests",
    "gpu: marks tests as requiring a GPU",
]

[tool.ruff]
target-version = "py312"
# fix = true

[tool.ruff.lint]
extend-select = ["UP", "E", "W", "F", "I", "SIM", "TID", "PTH", "PERF", "RUF"]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true
