[tool.pytest.ini_options]
pythonpath = "python/needle"
testpaths = "tests/"
addopts = [
    "-ras -n 8",
    "--strict-markers",
    "--strict-config",
    "-m 'not benchmark'",
    # "--import-mode=importlib",
]
markers = [
    "slow: marks tests as slow",
    "proptest: marks tests as property tests",
    "gpu: marks tests as requiring a GPU",
    "datasets: marks tests as requiring datasets",
    "benchmark: marks tests as benchmark tests",
]

[tool.ruff]
target-version = "py312"
# fix = true

[tool.ruff.lint]
extend-select = ["UP", "E", "W", "F", "I", "SIM", "TID", "PTH", "PERF", "RUF"]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true
