[package]
name = "ndarray_backend_cpu"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"]
# use clang because of C++ 20 modules features
# c_compiler = ["clang"]
# add optimization flags
env = { CXXFLAGS = "-O3 -march=native" }

[package.host-dependencies]
python = ">=3.13.5,<3.14"
cmake = ">=4.0.1,<5"
nanobind = ">=2.6.1,<2.8"
llvm-openmp = ">=20.1.7,<20.2"

[package.run-dependencies]
nanobind = ">=2.6.1,<2.8"
llvm-openmp = ">=20.1.7,<20.2"
