[project]
dependencies = ["numpy"]
name = "numpy_backend"
requires-python = ">= 3.13"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["numpy_backend"]
