---
name: Benchmark

on:
  workflow_call:
    inputs:
      python_changed:
        required: true
        type: boolean
      cpp_changed:
        required: true
        type: boolean
      cuda_changed:
        required: true
        type: boolean
      configs_changed:
        required: true
        type: boolean
  workflow_dispatch:

# on:
#   # run on pushes to the master branch
#   push:
#     branches:
#       - "main"
#   # run on pull requests
#   pull_request:
#   # `workflow_dispatch` allows codspeed to trigger
#   # performance analysis in order to generate initial data.
#   workflow_dispatch:

jobs:
  benchmark:
    if: inputs.python_changed == true ||
        inputs.cpp_changed == true ||
        inputs.cuda_changed == true ||
        inputs.configs_changed == true
    timeout-minutes: 30

    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
      - run: pixi install -e benchmark
      - run: pixi run build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pixi run benchmarks
          token: ${{ secrets.CODSPEED_TOKEN }}
