name: Benchmark

on:
  workflow_call:
    inputs:
      python_changed:
        required: true
        type: boolean
      cpp_changed:
        required: true
        type: boolean
      cuda_changed:
        required: true
        type: boolean
      configs_changed:
        required: true
        type: boolean

jobs:
  benchmark:
    if: inputs.python_changed == true ||
        inputs.cpp_changed == true ||
        inputs.cuda_changed == true ||
        inputs.configs_changed == true
    timeout-minutes: 20

    # Add explicit permissions
    permissions:
      actions: write
      checks: write
      contents: read
      pull-requests: write
      statuses: read

    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pixi run benchmarks
