name: Benchmark

on:
  workflow_call:
    inputs:
      python_changed:
        required: true
        type: boolean
      cpp_changed:
        required: true
        type: boolean
      cuda_changed:
        required: true
        type: boolean
      configs_changed:
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      python_changed:
        required: true
        type: boolean
      cpp_changed:
        required: true
        type: boolean
      cuda_changed:
        required: true
        type: boolean
      configs_changed:
        required: true
        type: boolean

permissions:
  contents: read
  pull-requests: write  # check-files
  checks: write         # test workflow
  issues: read          # test workflow

jobs:
  benchmark:
    if: inputs.python_changed == true ||
        inputs.cpp_changed == true ||
        inputs.cuda_changed == true ||
        inputs.configs_changed == true
    timeout-minutes: 30

    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pixi run benchmarks
          token: ${{ secrets.CODSPEED_TOKEN }}
