---
name: Benchmark

on:
  # run on pushes to the master branch
  push:
    branches: [main]
  # run on pull requests
  pull_request:
  # `workflow_dispatch` allows codspeed to trigger
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    timeout-minutes: 30

    name: "Run benchmarks (Shard #${{ matrix.shard }})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
      # the codspeed runner is slow, so do everything possible before
      - run: pixi install -e benchmark
      - run: pixi run build
      - run: pixi run download_mnist # for the mnist benchmarks

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pixi run benchmarks
               --test-group=${{ matrix.shard }} --test-group-count=4
          token: ${{ secrets.CODSPEED_TOKEN }}
