name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: lint
      - name: style
        run: pixi run style


  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Test
          uses: prefix-dev/setup-pixi@v0.8.1
          with:
            pixi-version: v0.40.3
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        - run: pixi run build


  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Test
          uses: prefix-dev/setup-pixi@v0.8.1
        # also runs slow tests
        - run: pixi run test_all
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
            files: |
              test-results/**/*.xml
              test-results/**/*.trx
              test-results/**/*.json

  test_numpy_backend:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set numpy backend
          run: echo "NEEDLE_BACKEND=numpy" >> "$GITHUB_ENV"
        - name: Test_numpy_backend
          uses: prefix-dev/setup-pixi@v0.8.1
        # also runs slow tests
        - run: pixi run test_all
