---
name: CI

on:
  push:
    branches: [main]
  pull_request:

# Cancel in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write  # check-files
  checks: write         # test workflow
  issues: read          # test workflow

jobs:
  check-skip-ci:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should-skip }}
    steps:
      - id: skip-check
        name: Check for skip-ci
        run: |
          # Debug: Print the commit message for troubleshooting
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          
          # Check commit message
          if [[ "${{ github.event.head_commit.message }}" =~ ^skip-ci ]] || 
             [[ "${{ github.event.head_commit.message }}" =~ \[skip-ci\] ]]; then
            echo "should-skip=true" >> $GITHUB_OUTPUT
            echo "Detected skip-ci in commit message, will skip all jobs"
            exit 0
          fi
          
          # Check PR title
          if [[ "${{ github.event.pull_request.title }}" =~ ^skip-ci ]] || 
             [[ "${{ github.event.pull_request.title }}" =~ \[skip-ci\] ]]; then
            echo "should-skip=true" >> $GITHUB_OUTPUT
            echo "Detected skip-ci in PR title, will skip all jobs"
            exit 0
          fi
          
          echo "should-skip=false" >> $GITHUB_OUTPUT
          echo "No skip-ci detected, continuing with all jobs"

  check-files:
    name: Check changed files
    uses: ./.github/workflows/check-changed-files.yml

  style:
    name: Style
    uses: ./.github/workflows/style.yml

  pyright:
    name: Pyright
    needs: [check-skip-ci, check-files]
    if: needs.check-skip-ci.outputs.should-skip != 'true'
    uses: ./.github/workflows/pyright.yml
    with:
      python_changed:
        ${{ needs.check-files.outputs.python_changed == 'true' }}

  build:
    name: Build
    needs: [check-skip-ci, check-files]
    if: needs.check-skip-ci.outputs.should-skip != 'true'
    uses: ./.github/workflows/build.yml
    with:
      cpp_changed:
        ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      configs_changed:
        ${{ needs.check-files.outputs.configs_changed == 'true'}}

  test:
    name: Test
    needs: [check-skip-ci, check-files]
    if: needs.check-skip-ci.outputs.should-skip != 'true'
    uses: ./.github/workflows/test.yml
    with:
      python_changed:
        ${{ needs.check-files.outputs.python_changed == 'true' }}
      cpp_changed:
        ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      cuda_changed:
        ${{ needs.check-files.outputs.cuda_changed == 'true' }}
      configs_changed:
        ${{ needs.check-files.outputs.configs_changed == 'true' }}

  benchmark:
    name: Benchmark
    needs: [check-skip-ci, check-files]
    if: needs.check-skip-ci.outputs.should-skip != 'true'
    uses: ./.github/workflows/benchmark.yml
    with:
      python_changed:
        ${{ needs.check-files.outputs.python_changed == 'true' }}
      cpp_changed:
        ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      cuda_changed:
        ${{ needs.check-files.outputs.cuda_changed == 'true' }}
      configs_changed:
        ${{ needs.check-files.outputs.configs_changed == 'true' }}
