name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'  # Ignore all Markdown files
  pull_request:
    paths-ignore:
      - '**.md'  # Ignore all Markdown files

# Cancel in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      only_docs: ${{ steps.filter.outputs.only_docs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for file changes
        id: filter
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.md$' && 
             ! git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qvE '\.md$'; then
            echo "only_docs=true" >> $GITHUB_ENV
            echo "::set-output name=only_docs::true"
          else
            echo "only_docs=false" >> $GITHUB_ENV
            echo "::set-output name=only_docs::false"
          fi  


  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add pre-commit cache step
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-

      - name: Lint
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: lint
          cache: true
      - name: style
        run: pixi run style


  build:
    needs: check-changes
    if: needs.check-changes.outputs.only_docs == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.3
          cache: true
          cache-write:
            ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: pixi run build

  test:
    needs: check-changes
    if: needs.check-changes.outputs.only_docs == 'false'

    timeout-minutes: 10

    strategy:
      matrix:
        backend: [nd, np]
      fail-fast: false
    runs-on: ubuntu-latest

    # test report needs write permissions
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Cache datasets
        uses: actions/cache@v4
        with:
          path: data
          key: ${{ runner.os }}-datasets-v1
          restore-keys: |
            ${{ runner.os }}-datasets-

      - name: Set backend
        run: echo "NEEDLE_BACKEND=${{ matrix.backend }}" >> "$GITHUB_ENV"
      - name: Test
        uses: prefix-dev/setup-pixi@v0.8.1
      - run: pixi run test_all

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: matrix.backend == 'nd' && always()
        with:
          files: |
            reports/test_report.xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.backend == 'nd' && always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: liskajiri/needle
          files: reports/coverage.xml

      - name: Upload test results to Codecov
        if: matrix.backend == 'nd' && always()
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: reports/test_report.xml
