name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: lint
      - name: pre-commit
        run: pixi run style


  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Test
          uses: prefix-dev/setup-pixi@v0.8.1
          with:
            pixi-version: v0.39.0
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        - run: pixi run test
