name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: lint
      - name: style
        run: pixi run style


  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install build tools
          run: sudo apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang

        - uses: actions/checkout@v4
        - name: Test
          uses: prefix-dev/setup-pixi@v0.8.1
          # with:
          #   pixi-version: v0.39.0
          #   cache: true
          #   cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        - run: pixi run build


  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Test
          uses: prefix-dev/setup-pixi@v0.8.1
          # with:
          #   pixi-version: v0.39.0
          #   cache: true
        # also runs slow tests
        - run: pixi run test_all
