---
name: CI

on:
  push:
    branches: [main]
  pull_request:

# Cancel in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write  # check-files
  checks: write         # test workflow
  issues: read          # test workflow

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      skip-ci: ${{ steps.check.outputs.skip-ci }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == "skip-ci"* ]] || [[ "${{ github.event.head_commit.message }}" == *"[skip-ci]"* ]]; then
            echo "skip-ci=true" >> $GITHUB_OUTPUT
          else
            echo "skip-ci=false" >> $GITHUB_OUTPUT
          fi

  check-files:
    name: Check changed files
    uses: ./.github/workflows/check-changed-files.yml

  style:
    name: Style
    uses: ./.github/workflows/style.yml

  pyright:
    name: Pyright
    needs: [check-commit-message, check-files]
    if: needs.check-commit-message.outputs.skip-ci != 'true'
    uses: ./.github/workflows/pyright.yml
    with:
      python_changed:
        ${{ needs.check-files.outputs.python_changed == 'true' }}

  build:
    name: Build
    needs: [check-commit-message, check-files]
    if: needs.check-commit-message.outputs.skip-ci != 'true'
    uses: ./.github/workflows/build.yml
    with:
      cpp_changed:
        ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      configs_changed:
        ${{ needs.check-files.outputs.configs_changed == 'true'}}

  test:
    name: Test
    needs: [check-commit-message, check-files]
    if: needs.check-commit-message.outputs.skip-ci != 'true'
    uses: ./.github/workflows/test.yml
    with:
      python_changed:
        ${{ needs.check-files.outputs.python_changed == 'true' }}
      cpp_changed:
        ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      cuda_changed:
        ${{ needs.check-files.outputs.cuda_changed == 'true' }}
      configs_changed:
        ${{ needs.check-files.outputs.configs_changed == 'true' }}

  benchmark:
    name: Benchmark
    needs: [check-commit-message, check-files]
    if: needs.check-commit-message.outputs.skip-ci != 'true'
    uses: ./.github/workflows/benchmark.yml
    with:
      python_changed:
        ${{ needs.check-files.outputs.python_changed == 'true' }}
      cpp_changed:
        ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      cuda_changed:
        ${{ needs.check-files.outputs.cuda_changed == 'true' }}
      configs_changed:
        ${{ needs.check-files.outputs.configs_changed == 'true' }}
