---
name: CI

on:
  push:
    branches: [main]
  pull_request:

# Cancel in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  check-files:
    uses: ./.github/workflows/check-changed-files.yml

  style:
    uses: ./.github/workflows/style.yml

  pyright:
    needs: check-files
    uses: ./.github/workflows/pyright.yml
    with:
      python_changed: ${{ needs.check-files.outputs.python_changed == 'true' }}

  build:
    needs: check-files
    uses: ./.github/workflows/build.yml
    with:
      cpp_changed: ${{ needs.check-files.outputs.cpp_changed == 'true' }}

  test:
    needs: check-files
    uses: ./.github/workflows/test.yml
    with:
      python_changed: ${{ needs.check-files.outputs.python_changed == 'true' }}
      cpp_changed: ${{ needs.check-files.outputs.cpp_changed == 'true' }}
      cuda_changed: ${{ needs.check-files.outputs.cuda_changed == 'true' }}
