---
name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: prefix-dev/setup-pixi@v0.8.5
      - name: lint
        run: pixi run lint
