---
name: Pyright Type Checking

on:
  workflow_call:
    inputs:
      python_changed:
        required: true
        type: boolean

jobs:
  type-check:
    if: inputs.python_changed == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Type check
        uses: prefix-dev/setup-pixi@v0.8.5
      - name: type-check
        run: pixi run type_check
