---
name: Style Check

on:
  workflow_call:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add pre-commit cache step
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-

      - name: Lint
        uses: prefix-dev/setup-pixi@v0.8.3
      - name: style
        run: pixi run style
